version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    container_name: ${PROJECT_NAME}-db
    image: mariadb:10.8.3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=daddits
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MARIADB_DATABASE=main
